

module.exports = {
  RECEIVE_POSTS: "RECEIVE_POSTS",
  RECEIVE_POST: "RECEIVE_POST",
  CREATE_POST: "CREATE_POST",
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  FETCH_ONE_POST: "FETCH_ONE_POST",
  RECEIVE_COMMENT: "RECEIVE_COMMENT",
  RECEIVE_LIKE: "RECEIVE_LIKE",
  REMOVE_LIKE: "REMOVE_LIKE"
};
